### ISSUE TITLE
Shoes?

### ISSUE THREAD

**Issue by sporty1013** [urigott/Gait-events-identification-algorithm#1]
I wonder whether this works well while wearing shoes. thanks.

**Comment by urigott** [comment]
> I wonder whether this works well while wearing shoes. thanks.

We didn't test it, but I believe it should work also with shoes. Please update if you give it a try, and what are your results!

**Comment by sporty1013** [comment]
Hi, I'm getting this error.. do you have any clue? thanks! 

LinAlgError: SVD did not converge in Linear Least Squares

** On entry to DGELSD, parameter number  6 had an illegal value

**Comment by urigott** [comment]
Not sure. Can you send the full error, with reference to which line of code?

**Comment by urigott** [comment]
> Not sure. Can you send the full error, with reference to which line of code?

The problem was that the algorithm was used to calculate gait events for one foot only. In that case, the code should be edited, or the CSV has to be filled with random values for the other (non-recorded) foot.
